### ISSUE TITLE
Use of buggy plugin gatsby-plugin-styled-jsx-postcss

### ISSUE THREAD

**Issue by edmcman** [baobabKoodaa/gatsby-starter-photo-book#11]
This project is using `gatsby-plugin-styled-jsx-postcss` which is known to cause lockups in some versions of nodejs and gatsbyjs.  For more information please see this issue: https://github.com/gatsbyjs/gatsby/issues/21885

**Comment by baobabKoodaa** [comment]
I believe I removed postcss from this project earlier (see issue https://github.com/baobabKoodaa/gatsby-starter-photo-book/issues/4)

If this project is still using postcss in some way, can you please show where/how?

**Comment by edmcman** [comment]
Issue #4 looks like the same one I was warning you about.  I got your project from https://www.gatsbyjs.org/starters?d=gatsby-plugin-styled-jsx-postcss  I am not sure if you control the plugins listed there or not; if so you might want to remove the reference to gatsby-plugin-styled-jsx-postcss.
