### ISSUE TITLE
Gatsby Develop stuck for hours

### ISSUE THREAD

**Issue by IMJONEZZ** [baobabKoodaa/gatsby-starter-photo-book#4]
Running gatsby develop gets stuck on "Build Development Bundle" for an infinite amount of time. I let it run for 54 hours just in case it was just taking a little bit longer than I expected.

npm start, npm run develop, npm run build also all get stuck (the first two end up running gatsby develop and the last one runs gatsby build).

**Comment by baobabKoodaa** [comment]
54 hours, wow you are one patient man! Thank you for reporting the issue. Unfortunately I haven't been able to reproduce it on my machine. Can you confirm that you are able to run `gatsby develop` on some other gatsby starters without any issues? Which version of npm are you using?

**Comment by IMJONEZZ** [comment]
Hi, I wish I were more patient, admittedly it only got that far because I forgot about it.

Confirmed, I tried running gatsby develop on a couple of other starters, and it took longer than I'm used to with npm, but it did start a development environment.

I'm using npm version 6.14.2

**Comment by sleeper** [comment]
Same here, running node 13.3.0 and yarn 1.21.1. Running `gatsby develop --verbose` does not bring more information.

**Comment by baobabKoodaa** [comment]
Thanks for reporting this. I need to find a way to reproduce this on my own machine.

**Comment by sleeper** [comment]
I can help if needed, but fairly new to gatsby (like started 3h ago ;)). Any hint on how I could debug/find out where it's looping/waiting?

**Comment by baobabKoodaa** [comment]
Hey, if you can help that would be great! Unfortunately I don't know enough about Gatsby's build process to have any good debug ideas. I do have some bad ideas though:
- We could try to set up some "dumbed down" versions of the project and see if they work. For example, a version that just renders a simple text page, but has the same dependencies and build system, is it gonna work? What if it has to render images too? Doing this, you could narrow down which particular thing causes it to break.
- Could try different node versions
- Could try to update all the dependencies (I have a feeling this would immediately fix this particular issue, but then various other things are going to break down and it will take time to fix those).

**Comment by IMJONEZZ** [comment]
I have a feeling that updating the dependencies may be the reason things aren't working.

Originally running `npm i` inside the project brought up a bunch of known errors (sharp for image processing on windows), so I deleted the package-lock.json file. That's the only way I was able to get `npm install` to work, but I have a feeling that that has something to do with why it isn't working now.

**Comment by sleeper** [comment]
I tried to update packages, even bypassing `package.json` ranges to install latest version of packages (`yarn upgrade --latest`), but this didn't change anything.

**Comment by sleeper** [comment]
OK, so I investigated a little bit more. 
Seems like the last message in terminal is:
`success run queries - 0.025s - 11/11 435.92/s
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
⠋ Building development bundle`

So, looking at the issues of styled-jsx-plugin-postcss, it seems it already has an issue opened as it hangs (giuseppeg/styled-jsx-plugin-postcss#32), which crosslink an issue opened on gatsby itself (gatsbyjs/gatsby#21885).

So all in all, seems not related to this starter ;)

**Comment by sleeper** [comment]
So it basically styled-jsx-plugin-postcss which is not working. giuseppeg/styled-jsx-plugin-postcss#31 is giving some information on how it could be fixed, but seems not an easy fix.

**Comment by baobabKoodaa** [comment]
Wow, thanks for researching this! Now that you identified the likely cuplrit, I'm sure we can figure this out.

**Comment by sleeper** [comment]
Tested this morning removing the option `styled-jsx-plugin-postcss` allows to go further then the "Building Development Bundle", resulting later on on 2 errors (`src/components/view.js: Nesting detected at 42:25.Unfortunately nesting is not supported by styled-jsx`for exemple).
Server is then running, but site is not working.

**Comment by baobabKoodaa** [comment]
Hey, I made a PR, can you check if it fixes the problem for you?

https://github.com/baobabKoodaa/gatsby-starter-photo-book/pull/5

Basically, I noticed I was not utilizing PostCSS features to any meaningful extent, so I decided to refactor the CSS a little bit so I could get rid of the PostCSS plugin. I ran into some issues with FlashCues (a minor visual feature on the site), but I never liked how that feature turned out anyway, so I decided to remove FlashCues instead of fixing the issue with them.

**Comment by sleeper** [comment]
That's probably the best way to fix it ;) I tried to apply the fix, but I'm still having the same `src/components/view.js: Nesting detected at 42:25. Unfortunately nesting is not supported by styled-jsx.` issue, and looking at the devtools console seems like common.js is basically an HTML file .. .So perhaps coming from my own config.
I'll try later on to start from a fresh page, with your fix applied.

**Comment by sleeper** [comment]
Kudos !! 
I cloned the repo (fresh start) and merged the PR locally: it's now working!
Thanks a lot!
